__author__ = 'rt'

from django.conf.urls import *
from myproject import models, views
from django.conf import settings
from django.contrib import admin
from myproject.views import BdAutocomplete, DesignationAutocomplete, ItemAutocomplete, BiodataAutocomplete, ClientsAutocomplete, InvoiceAutocomplete
admin.autodiscover()



urlpatterns = [
                           url(r'^admin', include(admin.site.urls)),
			   url(r'^assignauth/$', views.genauth, name='genauth'),
			   url(r'^genauth/(?P<id>\d+)/$', views.genauth, name='genauth'),
		url(r'^advsearch/$', views.advsearch, name='advsearch'),
		url(r'^advreport/$', views.advreport, name='advreport'),
		url(r'^post-applied/$', DesignationAutocomplete.as_view(), name='post-applied'),
		url(r'^bd-autocomplete/$', BdAutocomplete.as_view(), name='bd-autocomplete'),
		url(r'^client-autocomplete/$', ClientsAutocomplete.as_view(), name='client-autocomplete'),
		url(r'^designation-autocomplete/$', DesignationAutocomplete.as_view(), name='designation-autocomplete'),
 		url(r'^items-autocomplete/$', ItemAutocomplete.as_view(), name='items-autocomplete'),
		url(r'^invoice-autocomplete/$', InvoiceAutocomplete.as_view(), name='invoice-autocomplete'),
		url(r'^biodata-autocomplete/$', BiodataAutocomplete.as_view(), name='biodata-autocomplete'),
                url(r'^$', include(admin.site.urls)),
     		#url(r'^biodata/$', views.my_view, name='my_view'),
       		url(r'^gencert/$', views.gencert, name='gencert'),
                url(r'^gencerthome/$', views.gencerthome, name='gencerthome'),
		url(r'^readysupport/$', views.readysupport, name='readysupport'),
                url(r'^loginreport/$', views.loginreport, name='loginreport'),
		url(r'^saveatt/$', views.saveatt, name='saveatt'),
                url(r'^single_patrolling/(?P<id>\d+)/$', views.single_patrolling,
							name='single_patrolling'),
		url(r'^mobile_patrolling/(?P<id>\d+)/$', views.mobile_patrolling,
							name='mobile_patrolling'),
		url(r'^myprofile/$', views.myprofile, name='myprofile'),
 		url(r'^support/$', views.support, name='support'),
                url(r'^employee_attendance_bulk/$', views.employee_attendance_bulk,
						name='employee_attendance_bulk'),
		url(r'^gatepass_employee/$', views.employee_gatepass,
						name='employee_gatepass'),
		url(r'^gatepass_add/$', views.gatepass_add, name='gatepass_add'),
		url(r'^gatepass_edit/(?P<id>\d+)/$', views.gatepass_edit,
							name='gatepass_edit'),
		url(r'^master_delete/(?P<id>\d+)/$', views.master_delete,
								name='master_delete'),
		url(r'^master_edit/(?P<id>\d+)/$', views.master_edit,
							name='master_edit'),
		url(r'^employee_gatepass_delete/(?P<id>\d+)/$',
				views.employee_gatepass_delete, name='employee_gatepass_delete'),
		url(r'^clients_edit/(?P<id>\d+)/$', views.clients_edit, name='clients_edit'),
		url(r'^vendor_edit/(?P<id>\d+)/$', views.vendor_edit, name='vendor_edit'),
		url(r'^final_report_view/(?P<id>\d+)/$', views.final_report_view,
						name='final_report_view'),
		url(r'^trainee_attendance_view/(?P<id>\d+)/$',
				views.trainee_attendance_view, name='trainee_attendance_view'),		
		url(r'^discipline_add/$', views.discipline_add, name='discipline_add'),
		url(r'^ticket_add/$', views.ticket_add, name='ticket_add'),
		url(r'^client_add/$', views.client_add, name='client_add'),
		url(r'^vendor_add/$', views.vendor_add, name='vendor_add'),
		url(r'^master_type/$', views.master_type, name='master_type'),
		url(r'^master_add/$', views.master_add, name='master_add'),
		url(r'^trainer_add/$', views.trainer_add, name='trainer_add'),
		url(r'^trainer_settings/$', views.trainer_settings, name='trainer_settings'),
		url(r'^vendor_view/(?P<id>\d+)/$', views.vendor_view, name='vendor_view'),
		url(r'^clients_view/(?P<id>\d+)/$', views.client_view, name='client_view'),
		url(r'^biodata_view/(?P<id>\d+)/$', views.biodata_view, name='biodata_view'),
		url(r'^biodata_delete/(?P<id>\d+)/$', views.biodata_delete, name='biodata_delete'),
		url(r'^clients_delete/(?P<id>\d+)/$', views.client_delete, name='client_delete'),
		url(r'^trainer_edit/(?P<id>\d+)/$', views.trainer_edit, name='trainer_edit'),
		url(r'^trainer_delete/(?P<id>\d+)/$', views.trainer_delete, name='trainer_delete'),
		url(r'^reference_incentive_settings/$', views.reference_incentive_settings,
						name='reference_incentive_settings'),
		url(r'^incentive_add/$', views.incentive_add, name='incentive_add'),
		url(r'^incentive_edit/(?P<id>\d+)/$', views.incentive_edit, name='incentive_edit'),
		url(r'^incentive_delete/(?P<id>\d+)/$', views.incentive_delete, name='incentive_delete'),
		url(r'^employee_view/(?P<id>\d+)/$', views.employee_view, name='employee_view'),
		url(r'^employee_delete/(?P<id>\d+)/$', views.employee_delete, name='employee_delete'),
		url(r'^notice_delete/(?P<id>\d+)/$', views.notice_delete, name='notice_delete'),
		url(r'^notice_board_add/$', views.notice_board_add, name='notice_board_add'),
		#url(r'^visitor_add/(?P<guid>\d+)/$', views.visitor_add, name='visitor_add'),
		url(r'^visitor_add/$', views.visitor_add, name='visitor_add'),
		url(r'^task_add/$', views.task_add, name='task_add'),
		url(r'^trainee_attendance/$', views.trainee_attendance, name='trainee_attendance'),
		url(r'^outward_gatepass/$', views.outward_gatepass, name='outward_gatepass'),
		url(r'^manage_employee/$', views.manage_employee, name='manage_employee'),
		url(r'^manage_clients/$', views.manage_client, name='manage_client'),
		url(r'^manage_vendors_workshops/$', views.manage_vendor, name='manage_vendor'),
		url(r'^employee_attendance/$', views.employee_attendance, name='employee_attendance'),
		url(r'^task_management/$', views.task_management, name='task_management'),
		url(r'^task_view/(?P<id>\d+)/$', views.task_view, name='task_view'),
		url(r'^task_delete/(?P<id>\d+)/$', views.task_delete, name='task_delete'),
		url(r'^visitor_management/$', views.visitor_management, name='visitor_management'),
		url(r'^search_profile/$', views.search_profile, name='search_profile'),
		url(r'^customer_feedback/$', views.customer_feedback, name='customer_feedback'),
		url(r'^api/outward_gatepass/$', views.OutwardList.as_view()),
		url(r'^api/employee/$', views.EmployeeList.as_view()),
		url(r'^api/discipline/$', views.DisciplineList.as_view()),
		url(r'^api/client/$', views.ClientList.as_view()),
		url(r'^api/vendor/$', views.VendorList.as_view()),
		url(r'^api/visitor/$', views.VisitorList.as_view()),
		url(r'^api/task/$', views.TaskList.as_view()),
		url(r'^api/final_report/$', views.FinalReportList.as_view()),
		url(r'^api/notice_board/$', views.NoticeBoardList.as_view()),
		url(r'^api/support_ticket/$', views.SupportTicketList.as_view()),
		url(r'^api/attendance/$', views.EmployeeAttendanceList.as_view()),
		url(r'^api/biodata/$', views.BiodataList.as_view()),
		url(r'^api/customer_feedback/$', views.CustomerFeedbackList.as_view()),
		url(r'^api/gatepass/$', views.GatepassList.as_view()),			
		url(r'^discipline_compliance/$', views.discipline_compliance,
						name='discipline_compliance'),
		url(r'^notice_board/$', views.notice_board, name='notice_board'),
		url(r'^final_report/$', views.final_report, name='final_report'),
                url(r'^gatepass_employee/add/$', views.employee_gatepass_add,
							name='employee_gatepass_add'),
		#url(r'^(?P<model_name>\w+)$', views.readonly, name='readlony'),
                url(r'^empbulksearch/$', views.empbulksearch, name='empbulksearch'),
		url(r'^consultancy/$', views.consultancy, name='consultancy'),
		url(r'^loan_advance_setting/$', views.loan_advance_setting,
						name='loan_advance_setting'),
		url(r'^consultancy_add/$', views.consultancy_add, name='consultancy_add'),
		url(r'^consultancy_edit/(?P<id>\d+)/$', views.consultancy_edit,
						name='consultancy_edit'),
		url(r'^consultancy_delete/(?P<id>\d+)/$', views.consultancy_delete,
							name='consultancy_delete'),
		url(r'^loyality_bonus/$', views.loyality_bonus, name='loyality_bonus'),
		url(r'^loan_types/$', views.loan_types, name='loan_types'),
		url(r'^loan_types_add/$', views.loan_types_add, name='loan_types_add'),
		#url(r'^loan_types_edit/(?P<id>\d+)/$', views.loan_types_edit, name='loan_types_edit'),
		#url(r'^loan_types_delete/(?P<id>\d+)/$', views.loan_types_delete, name='loan_types_delete'),
		url(r'^loyality_bonus_add/$', views.loyality_bonus_add,
						name='loyality_bonus_add'),
		url(r'^loan_advance_setting_add/$', views.loan_advance_setting_add,
						name='loan_advance_setting_add'),
		url(r'^loan_advance_delete/(?P<id>\d+)/$', views.loan_advance_delete,
							name='loan_advance_delete'),
		url(r'^loyality_edit/(?P<id>\d+)/$', views.loyality_edit, name='loyality_edit'),
		url(r'^loyality_edit/(?P<id>\d+)/$', views.loyality_edit, name='loan_types_edit'),
		url(r'^loyality_delete/(?P<id>\d+)/$', views.loyality_delete, name='loyality_delete'),
		url(r'^incentive_setting_loc/$', views.incentive_setting_loc,
							name='incentive_setting_loc'),
		url(r'^locationwise_incentive_add/$', views.locationwise_incentive_add,
					name='locationwise_incentive_add'),
		url(r'^locationwise_incentive_edit/(?P<id>\d+)/$', views.locationwise_incentive_edit,
								name='locationwise_incentive_edit'),
		url(r'^locationwise_incentive_delete/(?P<id>\d+)/$', views.locationwise_incentive_delete,
							name='locationwise_incentive_delete'),
		url(r'^location_incentive_setting/$', views.location_incentive_setting,
									name='location_incentive_setting'),
		url(r'^location_setting_incentive_not_add/$', views.location_setting_incentive_not_add,
					name='location_setting_incentive_not_add'),
		url(r'^location_setting_incentive_not_delete/(?P<id>\d+)/$', views.location_setting_incentive_not_delete,
		 		name='location_setting_incentive_not_delete'),
                #url(r'^test/$', views.test, name='test'),
		url(r'^inward_others/$', views.inward_others, name='inward_others'),
		url(r'^inward_management/$', views.inward_stock, name='inward_stock'),
	        url(r'^outward_management/$', views.outward_management, name='outward_management'),
		 url(r'^acknowledgement/$', views.acknowledgement, name='acknowledgement'),
		 url(r'^cut_salary/$', views.cut_salary, name='cut_salary'),
		 url(r'^attendance_ho/$', views.attendance_ho, name='attendance_ho'),
		 url(r'^employee_leaves/$', views.employee_leaves, name='employee_leaves'),
		 url(r'^leaves_applications/$', views.leaves_applications, name='leaves_applications'),
		 url(r'^leaves_application_approval/$', views.leaves_application_approval,
								name='leaves_application_approval'),
		 url(r'^location_attendence/$', views.location_attendence, name='location_attendence'),
		 url(r'^location_incharge/$', views.location_incharge, name='location_incharge'),
		 url(r'^designation_payroll/$', views.designation_payroll, name='designation_payroll'),
		 url(r'^employee_wise/$', views.employee_wise, name='employee_wise'),
		 url(r'^photoupload/$', views.photoupload, name='photoupload'),
		 url(r'^police_verification/$', views.police_verification, name='police_verification'),
		 url(r'^police_verification_id/(?P<id>\d+)/$', views.police_verification_id,
							name='police_verification_id'),
		 url(r'^customer_feedback_id/(?P<id>\d+)/$', views.customer_feedback_id,
							name='customer_feedback_id'),
		 url(r'^rota_hours_exceeded/$', views.rota_hours_exceeded, name='rota_hours_exceeded'),
		 url(r'^send_sms/$', views.send_sms, name='send_sms'),
		 url(r'^separation/$', views.separation, name='separation'),
		 url(r'^staff_type/$', views.staff_type, name='staff_type'),
		 url(r'^manage_vendors_workshops/$', views.manage_vendors_workshops,
							name='manage_vendors_workshops'),
		 url(r'^manage_quotation/$', views.manage_quotation, name='manage_quotation'),
		 url(r'^work_order/$', views.client, name='client'),
		 url(r'^otallow_details/$', views.otallow_details, name='otallow_details'),
		 url(r'^editable_attendance/$', views.editable_attendance, name='editable_attendance'),
		 url(r'^employee_movement/$', views.employee_movement, name='employee_movement'),
		 url(r'^item_requisition_approve/$', views.item_requisition_approve,
								name='item_requisition_approve'),
		 url(r'^manage_item/$', views.manage_item, name='manage_item'),
   		 url(r'^manage_itemedit/(?P<id>\d+)/$', views.manage_itemedit, name='manage_itemedit'),
   		 #url(r'^idcard/(?P<id>\d+)$', views.getidcard, name='getidcard'),
   		 #url(r'^getidcard/(?P<id>\d+)/$', views.getidcard, name='getidcard'),
    		 url(r'^idcardform/$', views.idcardform, name='idcardform'),
		 url(r'^idcardreport/$', views.idcardreport, name='idcardreport'),
   		 url(r'^individual_issuance/$', views.individual_issuance,
				name='individual_issuance'),
  		 url(r'^issue_item_emp/$', views.issue_item_emp, name='issue_item_emp'),
  		 url(r'^manage_store/$', views.manage_store, name='manage_store'),
  		 url(r'^store_edit/(?P<id>\d+)/$', views.store_edit, name='store_edit'),
  		 url(r'^store_delete/(?P<id>\d+)/$', views.store_delete, name='store_delete'),
  		 url(r'^purchase_order/$', views.purchase_order, name='purchase_order'),
  		 url(r'^store_edit/(?P<id>\d+)/$', views.store_edit, name='store_edit'),
  		 url(r'^store_delete/(?P<id>\d+)/$', views.store_delete, name='store_delete'),
                 url(r'^item_requisition_assignment/$', views.item_requisition_assignment,
							name='item_requisition_assignment'),
		  
		 url(r'^advsearchform/$', views.advsearchform, name='advsearchform'),
		 url(r'^movementreport/$', views.movementreport, name='movementreport'),
		 url(r'^clientdetailsreport/$', views.clientdetailsreport, name='clientdetailsreport'),
		 url(r'^clientdetailsform/$', views.clientdetailsform, name='clientdetailsform'),
		 url(r'^authorisedstrengthreport/$', views.authorisedstrengthreport,
								name='authorisedstrengthreport'),
		 url(r'^authorisedstrengthform/$', views.authorisedstrengthform, name='authorisedstrengthform'),
		 url(r'^epfesireport/$', views.epfesireport, name='epfesireport'),
		 url(r'^epfesiform/$', views.epfesiform, name='epfesiform'),
		 url(r'^userlogform/$', views.userlogform, name='userlogform'),
                 url(r'^userlog/$', views.userlog, name='userlog'),
		 url(r'^trainingform/$', views.trainingform, name='trainingform'),
		 url(r'^trainingreport/$', views.trainingreport, name='trainingreport'),
                 url(r'^paymentfieldreport/$', views.paymentfieldreport, name='paymentfieldreport'),
		 url(r'^paymentfieldform/$', views.paymentfieldform, name='paymentfieldform'),
		 url(r'^locationattendancereport/$', views.locationattendancereport, name='locationattendancereport'),
		 url(r'^locationattendanceform/$', views.locationattendanceform, name='locationattendanceform'),
		 url(r'^otallowform/$', views.otallowform, name='otallowform'),
		 url(r'^otallow/$', views.otallow, name='otallow'),
		 url(r'^otnotform/$', views.otnotform, name='otnotform'),
		 url(r'^otnot/$', views.otnot, name='otnot'),
		 url(r'^specialfieldform/$', views.specialfieldform, name='specialfieldform'),
		 url(r'^specialfield/$', views.specialfield, name='specialfield'),
                 url(r'^webservices$', views.webservices, name='webservices'),
		 url(r'^tmpls/(?P<tname>.+)/$', views.tmpls, name='tmpls'),
		 #url(r'^assignauth/$', views.assignauth, name='assignauth'),
                 #url(r'^getcalevents/$', views.getcalevents, name='getcalevents'),


		 

      #  url(r'^myprofile/$', views.profile, name='myprofile'),
	#url(r'^gvmc-zones/$', views.gvmc, name='gvmc'),
       ## views.readobj, {'model': models.Train}),
        ]
